version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g serverless
      - npm install
      - sls -v
  pre_build:
      - aws configure set aws_access_key_id $ACCESS_KEY_ID --profile $AWS_PROFILE_NAME && aws configure set aws_secret_access_key $AWS_SECRET_KEY_ID --profile $AWS_PROFILE_NAME && aws configure set region $AWS_REGION --profile $AWS_PROFILE_NAME && aws configure set output $OUTPUT_FORMAT --profile $AWS_PROFILE_NAME
  build:
    commands:
      - serverless deploy --stage dev --aws-profile $AWS_PROFILE_NAME

cache:
  paths:
    - node_modules