version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g serverless@3.30.1
      - npm install
      - sls -v
  build:
    commands:
      - serverless deploy

cache:
  paths:
    - node_modules